### ISSUE TITLE
any way to use this live?

### ISSUE THREAD

**Issue by konsumer** [DjDeveloperr/deno-canvas#12]
When I first saw this, I thought it might be a way to open a live canvas context and draw on the screen. It seems like from the examples, it's all offline (create canvas, draw on it, then save image.)

Is there interest in a live canvas? I am pretty new to deno & rust, but have dabbled with rust, and have a lot of experience with node. I'd love to help. It'd be awesome to be able to make a fast native game with roughly the same API as browser. What would be involved? Maybe [sdl2](https://deno.land/x/sdl2@0.1-alpha.3) or something with [webgpu](https://github.com/denoland/deno/issues/7863)?

**Comment by DjDeveloperr** [comment]
You're right: this module quite only serves for server side image manipulation (at least for now). You can probably copy the image data to some window frame buffer or something, in fact I've done this exact before by putting raw image data on a window opened using `winit`, every frame. It just worked, but main problem is the copying going on when rendering it.

At the moment, WebGPU in Deno does not have any way to render to a window. There were little progress to support SwapChain for plugins which would allow rendering directly to a window, but as plugins died, so is the progress on that right now (which is pretty sad, I really wanted that...)

Btw as for `winit`, there used to be a plugin that wrapped `winit` and exposes TypeScript bindings. The plugin was [pane](https://deno.land/x/pane)), but no longer works because plugins were removed in favor of FFI, it might be ported to use FFI though.

**Comment by konsumer** [comment]
It seems like [sdl2](https://deno.land/x/sdl2@0.1-alpha.3) does not really have support for in-memory images (so I would need to make a new image file every frame, which just sounds horrible for performance and disk-thrashing.) More than that it uses a funny TCP-based interop system (rather than ffi or native plugin) so I dunno, it may be kind of a bad path. I have worked with SDL in the past, in C, and could probly make a simple little lib in rust that has a really simple api:

- make a window (with height/width/title/etc) and make image texture that fills screen
- update image texture & refresh screen (for running on change)

I like your idea of winit, too, but I can't quite tell what is needed to draw an image on the window.

**Comment by konsumer** [comment]
Ok! Here is what I'm gonna do:

I will make a deno FFI-wrapper lib for [minifb](https://github.com/emoon/minifb) that works with this lib. It has a very simple API, and is cross-platform. That way users can do offline rendering with canvas, as it is, or use that to make a window. Seems like a pretty good best-of-all-worlds solution, and it might be useful for other deno non-canvas things.

**Comment by konsumer** [comment]
Hmm, I fought with it for a long time, and limitations in deno ffi (no strings or arrays!) and my lack of familiarity with rust made this super-hard for me. My start to it is [here](https://github.com/konsumer/deno-minifb). I might come back to it, but this just seems impossibly stupid to get a really simple thing done.

**Comment by DjDeveloperr** [comment]
`minifb` looks really nice and perfect for this case! But yeah, then there's Deno FFI limitations.. strings and buffer support will yet be added (there is open PR). If Deno FFI supported getting pointer to JS allocated ArrayBuffer, it would be honestly so good. We could perhaps just get direct Array Buffer View for the WASM memory and pass it's pointer directly to `minifb`, zero copying. At this point due to the limitations it does seem impossible without doing some hacky workarounds which will do only the worse. We can only wait for better FFI support to be added yet.

**Comment by DjDeveloperr** [comment]
For this purpose, I've just added a `getRawBuffer` property which returns `Uint8Array` (pointing to WASM memory) containing underlying RGBA data. Let's wait for buffer support in FFI next 🙌

**Comment by DjDeveloperr** [comment]
![image](https://user-images.githubusercontent.com/43033058/132955116-1d95a9e2-80c7-4e02-b258-f6e307e00b65.png)

Playing around the buffers PR and your deno_minifb 👀

**Comment by konsumer** [comment]
That's awesome! How did you get it talking between deno & rust lib? That is where I gave up. I had a dymb little rust main that could popup a window like that, but couldn't figure out how to send a simple string for window-title, or a buffer that could be modified in deno-space.

**Comment by konsumer** [comment]
I think maybe my remaining issue is rust-side (and not knowing how to expose the right types), but it seems to me like this might be doable right now with a `UInt8Array` for title & the pixel-buffer, but I can't quite figure it out.

**Comment by konsumer** [comment]
I updated minifb to follow this, and it feels like I got a bit further, but I still get this error on deno-side:

```
error: TS2322 [ERROR]: Type '"buffer"' is not assignable to type 'NativeType'.
    parameters: ["buffer", "usize", "usize"],
```

This is with `deno 1.13.2 (release, x86_64-unknown-linux-gnu)`. Do I need another version?

**Comment by konsumer** [comment]
Ah, sorry, just looked closer at your screenshot. You are using `deno-ffi-buffers-pr`. Where can I find this?

**Comment by DjDeveloperr** [comment]
I've built Deno from this PR: https://github.com/denoland/deno/pull/11648

**Comment by DjDeveloperr** [comment]
So after investigating more, seems like `update_with_buffer` calls are very slow and end up hanging the thread.

**Comment by DjDeveloperr** [comment]
It was `limit_update_rate` causing this, lol. Now I'm banging my head against another big issue... either canvas buffer is not RGBA or update with buffer doesn't take RGBA buffer :/ I'm getting B color swapped with R

**Comment by DjDeveloperr** [comment]
So canvas buffer is for sure RGBA, but minifb seems to look for BGRA. I'm not sure how we can work around this..

**Comment by konsumer** [comment]
I think it's RGBA, but `u32` vs `u8`. As far as I can tell, it uses a RGBA buffer filled with `u32[width*height]` rather than `u8[height*width*4]`. 

I found this in the comments of the source:

```rust
fn from_u8_rgb(r: u8, g: u8, b: u8) -> u32 {
    let (r, g, b) = (r as u32, g as u32, b as u32);
         (r << 16) | (g << 8) | b
    }
```

**Comment by DjDeveloperr** [comment]
Ah, I think this probably has something to do with endianness since the `*const u8` I'm passing to Rust is probably being transmuted to `&[u32]` and causing the whole format to be reversed i.e. `0RGB`/`ARGB` -> `BGRA`/`BGR0`.
So we'll have to do manual conversion of `&[u8]` to `&[u32]`... it will make allocation but no other way around.

**Comment by DjDeveloperr** [comment]
So it's fixed by converting it to that 👀 

![image](https://user-images.githubusercontent.com/43033058/132978202-182f8c07-2a36-4fed-be5a-099e3d0fae64.png)

**Comment by konsumer** [comment]
Awesome! love to play with the code.

**Comment by konsumer** [comment]
You wanna PR to the window library?

**Comment by DjDeveloperr** [comment]
Yeah, I'll do PR in a bit

**Comment by konsumer** [comment]
I think I would like to eventually add the other minifb stuff (mouse and key handling, nostly, would be useful.) Without the PR being merged, and also no callbacks, it will probly take a bit for it to be useful, but it seems like a nice general but minimal cross-platform way to do this kind of thing.

**Comment by DjDeveloperr** [comment]
I have some ideas for event loop for mouse and key handling stuff, I would love to help with that

**Comment by konsumer** [comment]
Like I said, rust is not my strong-suit. I will add you as a collab, and dyou can do whatever makes sense, no PR needed.

**Comment by DjDeveloperr** [comment]
Since this feature is gonna be implemented by external libs, I'll close this issue for now

**Comment by konsumer** [comment]
Lately, I have been working on node-raylib (it needs to be updated to latest raylib), as an alternative, so I am happy to transfer deno-minifb to you, since you are doing all the work on it, anyway!

node-raylib isn't a nice familiar canvas API, but raylib runs very well on the pi, and is pretty simple to use, and node-raylib is still in javascript, so it should meet my needs of "easy to use library for making minigames on pi device", even if it does require learning a new js API to draw things on screen.

**Comment by andykais** [comment]
@konsumer deno sadly does not run on a raspberry pi https://github.com/denoland/deno/issues/2295

**Comment by konsumer** [comment]
bummer
